name: Build FFmpeg Ultimate

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -y build-essential yasm wget git nasm

      - name: Run Build Script
        run: |
          chmod +x ./build_ffmpeg.sh
          ./build_ffmpeg.sh

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-ultimate-v2
          path: build/output/
