name: Build FFmpeg Ultimate for Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config yasm wget bzip2 git nasm

      - name: Run Build Script
        run: |
          chmod +x ./build_ffmpeg.sh
          ./build_ffmpeg.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-ultimate-libs
          path: build/output/
          name: ffmpeg-android-libs-v2
          path: ffmpeg-*/android/
